//! The `base` package, equivalent to Krocy's `com.srfmolina.krocy.ui.base`.
//!
//! It contains the four building blocks:
//! - [`UiState`]  — marker trait for screen state.
//! - [`UiEvent`]  — marker trait for user/UI events.
//! - [`UiEffect`] — marker trait for one-shot side effects.
//! - [`BaseViewModel`] — the half of the base ViewModel you implement, plus the
//!   mechanical [`ViewModelCarrier`] supertrait (generated by the
//!   [`view_model!`](crate::view_model) macro), [`ViewModelCore`],
//!   [`use_view_model`] and [`use_effects`].

mod base_view_model;
#[macro_use]
mod macros;
mod ui_effect;
mod ui_event;
mod ui_state;

pub use base_view_model::{
    use_effects, use_view_model, BaseViewModel, ViewModelCarrier, ViewModelCore,
};
pub use ui_effect::UiEffect;
pub use ui_event::UiEvent;
pub use ui_state::UiState;
